<script lang="ts">
  type Row={id:string;startedAt:number;lastSeenAt:number;landingPath:string;lastPath:string;referrer:string;utmSource:string;utmCampaign:string;fbclid:string;events:number;pageViews:number;productViews:number;addToCart:number;cartViews:number;checkout:number;rageClicks:number;deadClicks:number;activeMs:number;maxScroll:number;exitStage:string;replayAvailable:boolean;purchased:boolean;priority:string;priorityScore:number};
  export let data:{rows:Row[];period:{range:string;label:string}};
  let focus:'priority'|'checkout'|'cart'|'product'|'all'='priority';
  $: visibleRows=data.rows.filter(r=>{if(focus==='all')return true;if(focus==='checkout')return !r.purchased&&r.checkout>0;if(focus==='cart')return !r.purchased&&r.addToCart>0&&r.checkout===0;if(focus==='product')return !r.purchased&&r.productViews>0&&r.addToCart===0;return !r.purchased&&r.productViews>0;});
  const duration=(row:Row)=>{const s=Math.max(0,Math.round((row.activeMs||(row.lastSeenAt-row.startedAt))/1000));return s<60?`${s}s`:`${Math.floor(s/60)}m ${s%60}s`;};
  const source=(r:Row)=>r.utmSource||(r.fbclid?'facebook':r.referrer?'referral':'direct');
  const intent=(r:Row)=>r.purchased?'Kupovina zabeležena':r.checkout>0?'🔥 Checkout bez završetka':r.addToCart>0?'🛒 ATC bez checkouta':r.productViews>0?'👟 Proizvod bez ATC':'Browse';
  const rangeHref=(r:string)=>`/sessions?range=${r}`;
</script>
<header><div class="eyebrow">STOREFRONT · CUSTOMER JOURNEYS</div><h1>Sesije kupaca</h1><p>Prvo vidi kupce najbliže kupovini, pa pusti replay njihovog stvarnog ponašanja.</p></header>
<nav class="periods"><a class:active={data.period.range==='today'} href={rangeHref('today')}>Danas</a><a class:active={data.period.range==='yesterday'} href={rangeHref('yesterday')}>Juče</a><a class:active={data.period.range==='7d'} href={rangeHref('7d')}>7 dana</a><a class:active={data.period.range==='30d'} href={rangeHref('30d')}>30 dana</a></nav>
<section class="summary"><div><span>Checkout bez završetka</span><b>{data.rows.filter(r=>!r.purchased&&r.checkout>0).length}</b><small>{data.period.label}</small></div><div><span>ATC bez checkouta</span><b>{data.rows.filter(r=>!r.purchased&&r.addToCart>0&&r.checkout===0).length}</b><small>dodao pa stao</small></div><div><span>Proizvod bez ATC</span><b>{data.rows.filter(r=>!r.purchased&&r.productViews>0&&r.addToCart===0).length}</b><small>gledao pa izašao</small></div><div><span>Replay spreman</span><b>{data.rows.filter(r=>r.replayAvailable).length}</b><small>može odmah</small></div></section>
<nav class="filters" aria-label="Filter sesija"><button class:active={focus==='priority'} on:click={()=>focus='priority'}>🔥 Najbitnije</button><button class:active={focus==='checkout'} on:click={()=>focus='checkout'}>Checkout</button><button class:active={focus==='cart'} on:click={()=>focus='cart'}>Add to cart</button><button class:active={focus==='product'} on:click={()=>focus='product'}>Proizvod</button><button class:active={focus==='all'} on:click={()=>focus='all'}>Sve sesije</button></nav>
<section class="explain"><b>Prioritet:</b> checkout bez završetka → ATC bez checkouta → proizvod bez ATC. Shopify porudžbine još nisu 100% povezane sa svakim browser session ID-em, zato „bez završetka“ tretiramo kao jak signal odustajanja, ne kao apsolutni dokaz.</section>
<section class="panel">{#if visibleRows.length}<div class="table-wrap"><table><thead><tr><th>Prioritet</th><th>Replay</th><th>Sesija</th><th>Izvor</th><th>Ulaz → izlaz</th><th>Aktivno</th><th>PDP</th><th>ATC</th><th>Checkout</th><th>Scroll</th><th>Problemi</th></tr></thead><tbody>{#each visibleRows as row}<tr class:priority={row.checkout>0||row.addToCart>0}><td><span class={`intent ${row.priority}`}>{intent(row)}</span></td><td>{#if row.replayAvailable}<a class="play" href={`/sessions/${row.id}/replay`}>▶ Pusti replay</a>{:else}<span class="wait">snimak nije dostupan</span>{/if}</td><td><a href={`/sessions/${row.id}`}><strong>{new Date(row.startedAt).toLocaleString('sr-RS')}</strong><small>Detalji →</small></a></td><td>{source(row)}{#if row.utmCampaign}<small>{row.utmCampaign}</small>{/if}</td><td><code>{row.landingPath}</code><small>→ {row.lastPath}</small></td><td>{duration(row)}</td><td>{row.productViews}</td><td>{row.addToCart}</td><td>{row.checkout}</td><td>{row.maxScroll}%</td><td class:hot={row.rageClicks+row.deadClicks>0}>{row.rageClicks} rage · {row.deadClicks} dead</td></tr>{/each}</tbody></table></div>{:else}<div class="empty">Nema sesija u ovom filteru i periodu.</div>{/if}</section>
<style>
header{margin-bottom:16px}h1{font-size:34px;margin:4px 0 8px;letter-spacing:-.04em}header p{color:#8f99a8}.eyebrow{font-size:11px;color:#7e8897;font-weight:800;letter-spacing:.12em}.periods,.filters{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.periods a,.filters button{border:1px solid #29303a;background:#0d1116;color:#9aa5b3;border-radius:10px;padding:9px 12px;font-weight:800;font-size:12px}.periods a.active,.filters button.active{background:#172614;border-color:#426735;color:#baff9b}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.summary div,.panel{background:#101318;border:1px solid #20242b;border-radius:16px;padding:16px}.summary span{display:block;color:#7f8997;font-size:11px;margin-bottom:7px}.summary b{font-size:22px}.summary small{display:block;color:#64707f;margin-top:5px;font-size:10px}.explain{padding:12px 14px;margin-bottom:12px;border-radius:12px;background:#15180f;border:1px solid #30351e;color:#a9b88d;font-size:11px;line-height:1.5}.panel{padding:20px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:13px 10px;border-bottom:1px solid #1e232a;white-space:nowrap}tr.priority{background:rgba(139,240,72,.018)}th{color:#77818f;font-size:10px;text-transform:uppercase}td:nth-child(5){min-width:300px;max-width:390px;overflow:hidden;text-overflow:ellipsis}small{display:block;color:#65707e;margin-top:4px;font-size:10px}code{color:#bcc5d2}.play{display:inline-block;background:#8bf048;color:#0b1408;font-weight:900;padding:7px 10px;border-radius:8px}.wait{color:#65707e;font-size:10px}.hot{color:#ff9a88;font-weight:800}.intent{font-size:10px;padding:6px 8px;border-radius:99px;background:#262b31;color:#aab2bd}.intent.product{background:#302a16;color:#e3cb6d}.intent.cart{background:#302316;color:#ffca7b}.intent.checkout{background:#321b1d;color:#ff9d9d;font-weight:900}.intent.converted{background:#17301d;color:#90ee86}.empty{padding:18px;background:#0c0f13;border:1px dashed #2a313a;border-radius:14px;color:#8e98a7}@media(max-width:850px){.summary{grid-template-columns:repeat(2,1fr)}}
</style>
