<script lang="ts">
  export let data:{shopify:{revenue:number;orders:number;aov:number;topTitle:string;topRevenue:number;topShare:number};storefront:{sessions:number;productViews:number;atcSessions:number;checkoutSessions:number;rageSessions:number};ads:{accountName:string;currency:string;adId:string;adName:string;spend:number;impressions:number;clicks:number;purchases:number;purchaseValue:number;ctr:number;cpc:number;roas:number}[]};
  const moneyRsd=(n:number)=>`${new Intl.NumberFormat('sr-RS').format(Math.round(n))} RSD`;const pct=(n:number)=>`${n.toFixed(1)}%`;const rate=(a:number,b:number)=>b?a/b*100:0;
  $: atcRate=rate(data.storefront.atcSessions,data.storefront.sessions);$: checkoutRate=rate(data.storefront.checkoutSessions,data.storefront.atcSessions);$: rageRate=rate(data.storefront.rageSessions,data.storefront.sessions);
  type Insight={level:'good'|'watch'|'action';title:string;body:string;evidence:string[];why:string;next:string[]};
  $: insights=(()=>{const out:Insight[]=[];
    if(!data.storefront.sessions)out.push({level:'action',title:'Nema dovoljno podataka o ponašanju kupaca',body:'Shopify prodaja se vidi, ali tracker nema dovoljno sesija za zaključke.',evidence:['7d Sessions: 0'],why:'Bez sesija ne možemo izračunati pouzdan ATC, checkout ni drop-off.',next:['Proveri tracker signal u Podešavanjima','Sačekaj prve realne posete']});
    else{
      if(atcRate<4)out.push({level:'action',title:'Add-to-cart stopa je niska',body:`Samo ${pct(atcRate)} sesija dodaje proizvod u korpu.`,evidence:[`Sesije: ${data.storefront.sessions}`,`ATC sesije: ${data.storefront.atcSessions}`,`ATC stopa: ${pct(atcRate)}`],why:'Veliki pad pre korpe obično znači da problem nastaje na proizvodnoj stranici ili ponudi, ali tracker ne može dokazati motiv kupca.',next:['Pregledaj Heatmaps za najgledanije PDP stranice','Proveri veličine, cenu, dostavu i CTA','Uporedi sesije koje su stigle 75%+ scrolla a nisu kliknule ATC']});
      if(data.storefront.atcSessions>0&&checkoutRate<35)out.push({level:'action',title:'Prevelik pad od korpe do checkouta',body:`Samo ${pct(checkoutRate)} ATC sesija nastavlja na checkout.`,evidence:[`ATC: ${data.storefront.atcSessions}`,`Checkout: ${data.storefront.checkoutSessions}`,`ATC → Checkout: ${pct(checkoutRate)}`],why:'Ovo je najjači signal da cart drawer, dostava ili checkout CTA mogu praviti trenje.',next:['Otvori sesije sa ATC bez checkouta','Proveri dead/rage klikove u cart draweru','Proveri jasnoću dostave i Checkout dugmeta']});
      if(rageRate>=5)out.push({level:'action',title:'Kupci imaju frustrirajuće klikove',body:`${pct(rageRate)} sesija ima rage-click.`,evidence:[`Rage sesije: ${data.storefront.rageSessions}`,`Sve sesije: ${data.storefront.sessions}`,`Rage stopa: ${pct(rageRate)}`],why:'Više brzih klikova na isto mesto često znači da element ne reaguje kako korisnik očekuje.',next:['Otvori Heatmaps i filtriraj rage/dead tačke','Otvori detalj sesije i pogledaj redosled događaja']});
    }
    if(data.shopify.topShare>=30&&data.shopify.topTitle)out.push({level:'watch',title:'Previše prihoda zavisi od jednog proizvoda',body:`${data.shopify.topTitle} nosi oko ${pct(data.shopify.topShare)} 30-dnevnog prihoda.`,evidence:[`30d Revenue: ${moneyRsd(data.shopify.revenue)}`,`Top proizvod: ${data.shopify.topTitle}`,`Udeo top proizvoda: ${pct(data.shopify.topShare)}`],why:'Ako taj model nestane sa stocka ili mu padne potražnja, ukupna prodaja može naglo pasti.',next:['Drži stock pod kontrolom','Testiraj slične modele i creative varijante']});
    for(const ad of data.ads.slice(0,8)){const label=`${ad.adName}${ad.accountName?` · ${ad.accountName}`:''}`;if(ad.spend>0&&ad.purchases===0&&ad.clicks>=15&&ad.ctr>=2)out.push({level:'action',title:`Klikovi dolaze, kupovine ne: ${label}`,body:`CTR ${pct(ad.ctr)}, ${ad.clicks} klikova i 0 pripisanih kupovina.`,evidence:[`Spend: ${ad.spend.toFixed(2)} ${ad.currency}`,`Impressions: ${ad.impressions}`,`Clicks: ${ad.clicks}`,`CTR: ${pct(ad.ctr)}`,`Purchases: ${ad.purchases}`],why:'Creative privlači pažnju, ali nakon klika dolazi do prekida. Treba razdvojiti da li je problem landing/PDP ili checkout.',next:['Otvori Oglasi i proveri landing views/ATC','Uporedi Shopify tracker sesije iz Facebook izvora','Ne povećavaj budžet dok funnel ne pokaže gde pada']});else if(ad.purchases>0&&ad.roas>=3)out.push({level:'good',title:`Jak ROAS: ${label}`,body:`ROAS je ${ad.roas.toFixed(2)}.`,evidence:[`Spend: ${ad.spend.toFixed(2)} ${ad.currency}`,`Purchases: ${ad.purchases}`,`Meta revenue: ${ad.purchaseValue.toFixed(2)} ${ad.currency}`,`ROAS: ${ad.roas.toFixed(2)}`],why:'Meta pripisuje višestruko veći prihod od potrošnje.',next:['Ako uzorak nije mali, skaliraj postepeno','Prati CPA i frequency posle promene budžeta']});}
    if(!out.length)out.push({level:'good',title:'Nema kritičnog signala',body:'Trenutni podaci ne pokazuju jasan problem.',evidence:[`30d orders: ${data.shopify.orders}`,`7d sessions: ${data.storefront.sessions}`],why:'Nijedan od ugrađenih pragova nije aktiviran.',next:['Nastavi da prikupljaš podatke','Prati promene po danima']});return out.slice(0,12);})();
</script>
<header><div class="eyebrow">0 € GROWTH ADVISOR</div><h1>Pametni saveti</h1><p>Svaki predlog možeš da otvoriš i vidiš tačno iz kojih brojki je izveden, zašto je označen i šta bih sledeće uradio.</p></header>
<section class="metrics"><div><span>30d prihod</span><b>{moneyRsd(data.shopify.revenue)}</b></div><div><span>30d porudžbine</span><b>{data.shopify.orders}</b></div><div><span>Prosečna porudžbina</span><b>{moneyRsd(data.shopify.aov)}</b></div><div><span>7d sesije</span><b>{data.storefront.sessions}</b></div></section>
<section class="panel"><div class="head"><div class="eyebrow">PRIORITETI</div><h2>Šta prvo da uradiš</h2></div><div class="cards">{#each insights as item}<details class:good={item.level==='good'} class:watch={item.level==='watch'} class:action={item.level==='action'}><summary><div><span class="badge">{item.level==='good'?'DOBRO':item.level==='watch'?'PRATI':'AKCIJA'}</span><h3>{item.title}</h3><p>{item.body}</p></div><b class="more">Detalji +</b></summary><div class="detail"><section><h4>Brojke koje su aktivirale savet</h4>{#each item.evidence as e}<div class="evidence">{e}</div>{/each}</section><section><h4>Zašto ovo znači nešto</h4><p>{item.why}</p></section><section><h4>Sledeći koraci</h4><ol>{#each item.next as n}<li>{n}</li>{/each}</ol></section><small>Ovo je preporuka iz statistike, ne tvrdnja o tome šta kupac misli. Za razlog odustajanja koristimo ponašajne signale, ne nagađamo nameru.</small></div></details>{/each}</div></section>
<section class="panel"><div class="head"><div class="eyebrow">FUNNEL · 7 DANA</div><h2>Brzi pregled sajta</h2></div><div class="mini-grid"><div><span>Sesije</span><b>{data.storefront.sessions}</b></div><div><span>PDP</span><b>{data.storefront.productViews}</b></div><div><span>ATC</span><b>{data.storefront.atcSessions}</b><small>{data.storefront.sessions?pct(atcRate):'—'}</small></div><div><span>Checkout</span><b>{data.storefront.checkoutSessions}</b><small>{data.storefront.atcSessions?pct(checkoutRate):'—'}</small></div><div><span>Rage-click</span><b>{data.storefront.rageSessions}</b><small>{data.storefront.sessions?pct(rageRate):'—'}</small></div></div></section>
<style>header{margin-bottom:22px;max-width:900px}h1{font-size:36px;margin:4px 0 8px;letter-spacing:-.04em}h2{font-size:20px;margin:4px 0 0}h3{font-size:15px;margin:8px 0 6px}h4{font-size:12px;margin:0 0 8px;color:#dce3ec}header p,details p{color:#8f99a8;line-height:1.55}.eyebrow{font-size:11px;color:#7e8897;font-weight:800;letter-spacing:.12em}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.metrics>div,.panel{background:#101318;border:1px solid #20242b;border-radius:16px;padding:16px}.metrics span,.mini-grid span{display:block;color:#7f8997;font-size:11px;margin-bottom:8px}.metrics b{font-size:20px}.panel{padding:20px;margin-bottom:12px}.head{margin-bottom:14px}.cards{display:grid;gap:10px}.cards details{background:#0b0e12;border:1px solid #242a32;border-radius:14px;padding:0}.cards details.good{border-color:#29442c}.cards details.watch{border-color:#4c4021}.cards details.action{border-color:#55302f}.cards summary{display:flex;justify-content:space-between;gap:20px;padding:15px;cursor:pointer;list-style:none}.cards summary::-webkit-details-marker{display:none}.badge{display:inline-block;font-size:9px;font-weight:900;letter-spacing:.1em;padding:5px 7px;border-radius:99px;background:#242a32;color:#aeb7c4}.good .badge{background:#15301b;color:#9df08e}.watch .badge{background:#302912;color:#f0d77b}.action .badge{background:#32191b;color:#ff9c9c}.more{font-size:11px;color:#8bf048;white-space:nowrap}.detail{border-top:1px solid #20262d;padding:15px;display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.detail section{background:#101318;border:1px solid #20262d;border-radius:12px;padding:12px}.detail p,.detail li{font-size:12px;color:#aab3bf;line-height:1.5}.detail ol{padding-left:18px;margin:0}.evidence{font-size:12px;color:#d8e0ea;padding:7px 8px;background:#0c0f13;border-radius:8px;margin:5px 0}.detail>small{grid-column:1/-1;color:#6f7987}.mini-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.mini-grid div{background:#0b0e12;border:1px solid #20252c;border-radius:12px;padding:12px}.mini-grid b{font-size:18px}.mini-grid small{display:block;color:#8f99a8;margin-top:4px}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}.detail{grid-template-columns:1fr}.mini-grid{grid-template-columns:repeat(2,1fr)}} </style>
