import type { PageServerLoad } from './$types';
import { analyticsPeriod, dayKey } from '$lib/server/period';

type Row={accountId:string;accountName:string;currency:string;campaignId:string;campaignName:string;adsetId:string;adsetName:string;adId:string;name:string;spend:number;impressions:number;reach:number;frequency:number;clicks:number;linkClicks:number;landingPageViews:number;addToCart:number;checkouts:number;purchases:number;revenue:number;ctr:number;cpc:number;cpm:number;linkCtr:number;landingRate:number;atcRate:number;checkoutRate:number;purchaseRate:number;roas:number;cpa:number};

export const load:PageServerLoad=async({platform,url})=>{
  const period=analyticsPeriod(url),db=platform?.env?.DB;
  const emptyTotals={spend:0,impressions:0,reach:0,clicks:0,linkClicks:0,landingPageViews:0,addToCart:0,checkouts:0,purchases:0,revenue:0,ctr:0,cpc:0,cpm:0,frequency:0,roas:0,cpa:0};
  const since=dayKey(period.start),until=dayKey(Math.max(period.start,period.end-1));
  const empty={lastSyncAt:null as number|null,range:{since,until},rows:[] as Row[],totals:emptyTotals,currency:'',mixedCurrency:false,period};
  if(!db)return empty;
  const[result,sync]=await Promise.all([
    db.prepare(`SELECT account_id,MAX(account_name) account_name,MAX(currency) currency,MAX(campaign_id) campaign_id,MAX(campaign_name) campaign_name,MAX(adset_id) adset_id,MAX(adset_name) adset_name,ad_id,MAX(ad_name) ad_name,SUM(spend) spend,SUM(impressions) impressions,SUM(reach) reach,CASE WHEN SUM(impressions)>0 THEN SUM(frequency*impressions)/SUM(impressions) ELSE 0 END frequency,SUM(clicks) clicks,SUM(link_clicks) link_clicks,SUM(landing_page_views) landing_page_views,SUM(add_to_cart) add_to_cart,SUM(checkouts) checkouts,SUM(purchases) purchases,SUM(purchase_value) purchase_value FROM meta_daily WHERE day BETWEEN ?1 AND ?2 GROUP BY account_id,ad_id ORDER BY spend DESC LIMIT 150`).bind(since,until).all(),
    db.prepare(`SELECT last_success_at FROM sync_state WHERE provider='meta'`).first<{last_success_at:number|null}>()
  ]);
  const rows:Row[]=(result.results as any[]).map(r=>{const spend=Number(r.spend||0),impressions=Number(r.impressions||0),reach=Number(r.reach||0),clicks=Number(r.clicks||0),linkClicks=Number(r.link_clicks||0),landingPageViews=Number(r.landing_page_views||0),addToCart=Number(r.add_to_cart||0),checkouts=Number(r.checkouts||0),purchases=Number(r.purchases||0),revenue=Number(r.purchase_value||0);return{accountId:String(r.account_id||''),accountName:String(r.account_name||r.account_id||''),currency:String(r.currency||''),campaignId:String(r.campaign_id||''),campaignName:String(r.campaign_name||''),adsetId:String(r.adset_id||''),adsetName:String(r.adset_name||''),adId:String(r.ad_id||''),name:String(r.ad_name||'Unnamed ad'),spend,impressions,reach,frequency:Number(r.frequency||0),clicks,linkClicks,landingPageViews,addToCart,checkouts,purchases,revenue,ctr:impressions?clicks/impressions*100:0,cpc:clicks?spend/clicks:0,cpm:impressions?spend/impressions*1000:0,linkCtr:impressions?linkClicks/impressions*100:0,landingRate:linkClicks?landingPageViews/linkClicks*100:0,atcRate:landingPageViews?addToCart/landingPageViews*100:0,checkoutRate:addToCart?checkouts/addToCart*100:0,purchaseRate:clicks?purchases/clicks*100:0,roas:spend?revenue/spend:0,cpa:purchases?spend/purchases:0};});
  const currencies=[...new Set(rows.map(r=>r.currency).filter(Boolean))],mixedCurrency=currencies.length>1,currency=currencies.length===1?currencies[0]:'';
  const raw=rows.reduce((a,r)=>({spend:a.spend+r.spend,impressions:a.impressions+r.impressions,reach:a.reach+r.reach,clicks:a.clicks+r.clicks,linkClicks:a.linkClicks+r.linkClicks,landingPageViews:a.landingPageViews+r.landingPageViews,addToCart:a.addToCart+r.addToCart,checkouts:a.checkouts+r.checkouts,purchases:a.purchases+r.purchases,revenue:a.revenue+r.revenue,weightedFrequency:a.weightedFrequency+r.frequency*r.impressions}),{spend:0,impressions:0,reach:0,clicks:0,linkClicks:0,landingPageViews:0,addToCart:0,checkouts:0,purchases:0,revenue:0,weightedFrequency:0});
  const totals={...raw,ctr:raw.impressions?raw.clicks/raw.impressions*100:0,cpc:raw.clicks?raw.spend/raw.clicks:0,cpm:raw.impressions?raw.spend/raw.impressions*1000:0,frequency:raw.impressions?raw.weightedFrequency/raw.impressions:0,roas:raw.spend?raw.revenue/raw.spend:0,cpa:raw.purchases?raw.spend/raw.purchases:0};
  return{lastSyncAt:Number(sync?.last_success_at||0)||null,range:{since,until},rows,totals,currency,mixedCurrency,period};
};
