import type { PageServerLoad } from './$types';
import { validOrderSql } from '$lib/server/orders';

const TZ='Europe/Belgrade';
const DAY=86400000;
const fxCache=new Map<string,{rate:number,at:number,approx:boolean}>();
function dayKey(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value||'';return`${g('year')}-${g('month')}-${g('day')}`;}
function zonedStart(key:string){const [y,m,d]=key.split('-').map(Number);let guess=Date.UTC(y,m-1,d);const p=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess));const n=(t:string)=>Number(p.find(x=>x.type===t)?.value||0);const represented=Date.UTC(n('year'),n('month')-1,n('day'),n('hour'),n('minute'),n('second'));return guess-(represented-guess);}
function periodFor(range:string){const now=Date.now(),todayStart=zonedStart(dayKey(now));if(range==='today')return{range,start:todayStart,end:now,label:'Danas'};if(range==='yesterday'){const y=zonedStart(dayKey(todayStart-1));return{range,start:y,end:todayStart,label:'Juče'};}if(range==='30d')return{range,start:now-30*DAY,end:now,label:'30 dana'};return{range:'7d',start:now-7*DAY,end:now,label:'7 dana'};}
async function fxRate(fetchFn:typeof fetch,from:string,to:string){if(!from||!to||from===to)return{rate:1,approx:false};const key=`${from}:${to}`,cached=fxCache.get(key);if(cached&&Date.now()-cached.at<6*3600000)return cached;try{const r=await fetchFn(`https://open.er-api.com/v6/latest/${encodeURIComponent(from)}`,{headers:{Accept:'application/json'}});if(r.ok){const j=await r.json() as any,rate=Number(j?.rates?.[to]);if(Number.isFinite(rate)&&rate>0){const v={rate,at:Date.now(),approx:false};fxCache.set(key,v);return v;}}}catch{}const fallback=(from==='USD'&&to==='RSD')?100:(from==='RSD'&&to==='USD')?0.01:1;const v={rate:fallback,at:Date.now(),approx:true};fxCache.set(key,v);return v;}
function emptyData(error:string|null=null){return{live:false,error,period:{range:'7d',label:'7 dana'},shopCurrency:'RSD',metaCurrencies:[] as string[],displayCurrency:'RSD',fxApprox:false,fxRates:{} as Record<string,number>,overview:{revenue:0,spend:0,roas:0,orders:0,conversionRate:0,cpa:0,sessions:0,addToCart:0,checkout:0,avgSessionActiveMs:0},behavior:{topTimePath:'',topTimeAvgMs:0,topTimeSessions:0,topExitPath:'',topExitCount:0,topExitShare:0},trend:[] as {label:string;revenue:number;spend:number}[],ads:[] as {name:string;spend:number;revenue:number;purchases:number;ctr:number;cpc:number;cpm:number;atcRate:number;currency:string}[]};}

export const load:PageServerLoad=async({platform,url,fetch})=>{
  const db=platform?.env?.DB;if(!db)return emptyData('D1 database nije povezana.');const period=periodFor(url.searchParams.get('range')||'7d');
  try{
    const fromKey=dayKey(period.start),trackerFrom=period.start;
    const [ordersResult,sessionsResult,eventsResult,sessionActiveResult,pageHealthResult,lastPathResult,metaResult,adResult]=await Promise.all([
      db.prepare(`SELECT created_at,total,currency FROM shopify_orders WHERE created_at>=?1 AND created_at<?2 AND ${validOrderSql()} ORDER BY created_at ASC`).bind(period.start,period.end).all(),
      db.prepare(`SELECT id,started_at FROM sessions WHERE started_at>=?1 AND started_at<?2`).bind(period.start,period.end).all(),
      db.prepare(`SELECT session_id,type,event_ts FROM events WHERE event_ts>=?1 AND event_ts<?2 AND type IN ('add_to_cart','checkout_started')`).bind(period.start,period.end).all(),
      db.prepare(`SELECT session_id,SUM(page_active) AS active_ms FROM (SELECT session_id,path,MAX(CASE WHEN type IN ('heartbeat','page_exit') THEN CAST(json_extract(meta_json,'$.activeMs') AS INTEGER) ELSE 0 END) AS page_active FROM events WHERE event_ts>=?1 AND event_ts<?2 GROUP BY session_id,path) GROUP BY session_id`).bind(period.start,period.end).all(),
      db.prepare(`SELECT path,COUNT(*) AS sessions,AVG(active_ms) AS avg_active,SUM(active_ms) AS total_active FROM (SELECT session_id,path,MAX(CASE WHEN type IN ('heartbeat','page_exit') THEN CAST(json_extract(meta_json,'$.activeMs') AS INTEGER) ELSE 0 END) AS active_ms FROM events WHERE event_ts>=?1 AND event_ts<?2 GROUP BY session_id,path) WHERE active_ms>0 GROUP BY path ORDER BY total_active DESC LIMIT 20`).bind(period.start,period.end).all(),
      db.prepare(`SELECT last_path,COUNT(*) AS exits FROM (SELECT s.id,(SELECT e.path FROM events e WHERE e.session_id=s.id AND e.event_ts<?2 ORDER BY e.event_ts DESC,e.id DESC LIMIT 1) AS last_path FROM sessions s WHERE s.started_at>=?1 AND s.started_at<?2) WHERE last_path IS NOT NULL GROUP BY last_path ORDER BY exits DESC LIMIT 20`).bind(period.start,period.end).all(),
      db.prepare(`SELECT day,currency,spend,purchases,purchase_value FROM meta_daily WHERE day>=?1 AND day<=?2 ORDER BY day ASC`).bind(fromKey,dayKey(period.end)).all(),
      db.prepare(`SELECT account_id,MAX(account_name) AS account_name,ad_id,MAX(ad_name) AS ad_name,MAX(currency) AS currency,SUM(spend) AS spend,SUM(impressions) AS impressions,SUM(clicks) AS clicks,SUM(add_to_cart) AS add_to_cart,SUM(landing_page_views) AS landing_page_views,SUM(purchases) AS purchases,SUM(purchase_value) AS purchase_value FROM meta_daily WHERE day>=?1 AND day<=?2 GROUP BY account_id,ad_id ORDER BY spend DESC LIMIT 12`).bind(fromKey,dayKey(period.end)).all()
    ]);
    const orderRows=ordersResult.results as any[],orders=orderRows.length,revenue=orderRows.reduce((s,r)=>s+Number(r.total||0),0),shopCurrencies=[...new Set(orderRows.map(r=>String(r.currency||'')).filter(Boolean))],shopCurrency=shopCurrencies.length===1?shopCurrencies[0]:'RSD',displayCurrency=shopCurrency||'RSD';
    const sessionRows=sessionsResult.results as any[],sessions=sessionRows.length,sessionIds=new Set(sessionRows.map(r=>String(r.id))),atcSessions=new Set<string>(),checkoutSessions=new Set<string>();for(const row of eventsResult.results as any[]){const sid=String(row.session_id||'');if(!sid||!sessionIds.has(sid))continue;if(row.type==='add_to_cart')atcSessions.add(sid);if(row.type==='checkout_started')checkoutSessions.add(sid);}const addToCart=atcSessions.size,checkout=checkoutSessions.size;
    const activeRows=sessionActiveResult.results as any[],avgSessionActiveMs=activeRows.length?activeRows.reduce((s,r)=>s+Number(r.active_ms||0),0)/activeRows.length:0;
    const metaRows=metaResult.results as any[],metaCurrencies=[...new Set(metaRows.map(r=>String(r.currency||'')).filter(Boolean))],rates:Record<string,number>={},approxFlags:boolean[]=[];for(const c of metaCurrencies){const fx=await fxRate(fetch,c,displayCurrency);rates[c]=fx.rate;approxFlags.push(fx.approx);}const converted=(value:number,currency:string)=>Number(value||0)*(rates[currency]??(currency===displayCurrency?1:1));
    const spend=metaRows.reduce((s,r)=>s+converted(Number(r.spend||0),String(r.currency||displayCurrency)),0),metaPurchases=metaRows.reduce((s,r)=>s+Number(r.purchases||0),0),metaRevenue=metaRows.reduce((s,r)=>s+converted(Number(r.purchase_value||0),String(r.currency||displayCurrency)),0),roas=spend>0?metaRevenue/spend:0,cpa=metaPurchases>0?spend/metaPurchases:0,conversionRate=sessions>0?orders/sessions*100:0;
    const keys:string[]=[],trend:{label:string;revenue:number;spend:number}[]=[];if(period.range==='today'||period.range==='yesterday'){const key=dayKey(period.start);keys.push(key);trend.push({label:period.label,revenue:0,spend:0});}else{const days=period.range==='30d'?30:7;for(let i=days-1;i>=0;i--){const d=Date.now()-i*DAY,key=dayKey(d);keys.push(key);trend.push({label:new Intl.DateTimeFormat('sr-RS',{timeZone:TZ,day:'2-digit',month:'2-digit'}).format(new Date(d)),revenue:0,spend:0});}}
    for(const row of orderRows){const idx=keys.indexOf(dayKey(Number(row.created_at)));if(idx>=0)trend[idx].revenue+=Number(row.total||0);}for(const row of metaRows){const idx=keys.indexOf(String(row.day||''));if(idx>=0)trend[idx].spend+=converted(Number(row.spend||0),String(row.currency||displayCurrency));}
    const ads=(adResult.results as any[]).map(row=>{const impressions=Number(row.impressions||0),clicks=Number(row.clicks||0),adSpend=Number(row.spend||0),lpv=Number(row.landing_page_views||0),atc=Number(row.add_to_cart||0);return{name:String(row.ad_name||'Unnamed ad'),spend:adSpend,revenue:Number(row.purchase_value||0),purchases:Number(row.purchases||0),ctr:impressions?clicks/impressions*100:0,cpc:clicks?adSpend/clicks:0,cpm:impressions?adSpend/impressions*1000:0,atcRate:lpv?atc/lpv*100:0,currency:String(row.currency||'')};});
    const topTime=(pageHealthResult.results as any[])[0]||{},exitRows=lastPathResult.results as any[],topExit=exitRows[0]||{},exitTotal=exitRows.reduce((s,r)=>s+Number(r.exits||0),0);
    return{live:true,error:null,period,shopCurrency,metaCurrencies,displayCurrency,fxApprox:approxFlags.some(Boolean),fxRates:rates,overview:{revenue,spend,roas,orders,conversionRate,cpa,sessions,addToCart,checkout,avgSessionActiveMs},behavior:{topTimePath:String(topTime.path||''),topTimeAvgMs:Number(topTime.avg_active||0),topTimeSessions:Number(topTime.sessions||0),topExitPath:String(topExit.last_path||''),topExitCount:Number(topExit.exits||0),topExitShare:exitTotal?Number(topExit.exits||0)/exitTotal*100:0},trend,ads};
  }catch(e){console.error('Growth overview load failed',e);const d=emptyData(e instanceof Error?e.message:'Overview data load failed');d.period={range:period.range,label:period.label};return d;}
};
