<script lang="ts">
  export let data:{sessions:number;productViews:number;addToCart:number;checkout:number;purchases:number;revenue:number;trackerReady:boolean;period:{label:string}};
  const money=(n:number)=>`${new Intl.NumberFormat('sr-RS').format(Math.round(n))} RSD`;
  const rate=(a:number,b:number)=>b>0?`${((a/b)*100).toFixed(1)}%`:'—';
</script>
<header><div class="eyebrow">{data.period.label.toUpperCase()} · EUROPE/BELGRADE</div><h1>Prodajni levak</h1><p>Tačno vidiš koliko kupaca prelazi iz pregleda proizvoda u korpu, checkout i realizovanu porudžbinu.</p></header>
<section class="panel"><div class="steps"><div><span>Sesije</span><b>{data.sessions}</b><small>početak</small></div><i>→</i><div><span>PDP</span><b>{data.productViews}</b><small>{rate(data.productViews,data.sessions)} sesija</small></div><i>→</i><div><span>Add to cart</span><b>{data.addToCart}</b><small>{rate(data.addToCart,data.productViews)} PDP</small></div><i>→</i><div><span>Checkout</span><b>{data.checkout}</b><small>{rate(data.checkout,data.addToCart)} ATC</small></div><i>→</i><div><span>Preuzete porudžbine</span><b>{data.purchases}</b><small>{data.checkout?rate(data.purchases,data.checkout):'validne samo'}</small></div></div><div class="revenue"><span>Realizovan Shopify prihod</span><strong>{money(data.revenue)}</strong></div></section>
{#if !data.trackerReady}<section class="notice"><b>Nema storefront sesija u ovom periodu.</b> Shopify realizovane porudžbine se i dalje vide odvojeno.</section>{/if}
<section class="hint">Prihod i porudžbine ovde nikad ne uključuju otkazane, refundirane, vraćene ili neispunjene porudžbine.</section>
<style>
header{margin-bottom:20px}h1{font-size:36px;margin:4px 0 8px;letter-spacing:-.05em}header p{color:#8f99a8;max-width:760px;line-height:1.55}.eyebrow{font-size:11px;color:#7e8897;font-weight:800;letter-spacing:.12em}.panel{background:#101318;border:1px solid #20242b;border-radius:18px;padding:22px}.steps{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr auto 1fr;gap:10px;align-items:center}.steps div{background:#0c0f13;border:1px solid #1c2128;border-radius:14px;padding:18px;text-align:center;transition:.2s ease}.steps div:hover{border-color:#35402f;transform:translateY(-2px)}.steps span,.steps small{display:block;color:#7f8997}.steps span{font-size:11px;margin-bottom:8px}.steps b{font-size:28px}.steps small{font-size:10px;margin-top:6px}.steps i{font-style:normal;color:#4a5360}.revenue{margin-top:18px;padding:15px 16px;border-radius:12px;background:#101a10;border:1px solid #213321;color:#9bc88d;display:flex;justify-content:space-between;gap:12px}.revenue strong{color:#c9ffb7}.notice,.hint{margin-top:12px;padding:16px;border-radius:14px;line-height:1.5}.notice{background:#2a2415;border:1px solid #4a3d1d;color:#efd98c}.hint{background:#0d1116;border:1px solid #202731;color:#7f8997;font-size:12px}@media(max-width:1000px){.steps{grid-template-columns:1fr}.steps i{transform:rotate(90deg);text-align:center}}@media(max-width:700px){.panel{padding:14px}.steps{gap:6px}.steps div{padding:14px}.steps b{font-size:24px}.revenue{flex-direction:column}.notice,.hint{font-size:12px;padding:13px}}
</style>
