<script lang="ts">
  import { onMount } from 'svelte';
  type ReplayEvent={kind:string;t:number;html?:string;path?:string;vw?:number;vh?:number;x?:number;y?:number;label?:string;state?:string;device?:string;dpr?:number};
  export let data:{session:{id:string;startedAt:number;lastSeenAt:number;landingPath:string;utmSource:string;utmCampaign:string;fbclid:string;purchased:boolean};events:ReplayEvent[];bytes:number;chunks:number;recordedSnapshots:number};
  let frame:HTMLIFrameElement;let playing=false;let speed=1;let elapsed=0;let duration=0;let cursorX=0;let cursorY=0;let cursorVisible=false;let clickPulse=false;let currentPath=data.session.landingPath;let viewportW=390;let viewportH=844;let device='mobile';let index=0;let startedWall=0;let startedElapsed=0;let raf=0;let pendingScrollX=0;let pendingScrollY=0;let visualReady=false;
  const firstT=data.events[0]?.t||data.session.startedAt;const lastT=data.events[data.events.length-1]?.t||data.session.lastSeenAt||firstT;duration=Math.max(0,lastT-firstT);
  const firstViewport=data.events.find((e)=>e.kind==='viewport'||e.kind==='snapshot');if(firstViewport){viewportW=Math.max(240,Number(firstViewport.vw||viewportW));viewportH=Math.max(320,Number(firstViewport.vh||viewportH));device=firstViewport.device||((viewportW<768)?'mobile':viewportW<1100?'tablet':'desktop');}
  const fmt=(ms:number)=>{const s=Math.max(0,Math.round(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
  const visualUrl=(path:string)=>`/heatmaps/snapshot?path=${encodeURIComponent(path||'/')}`;
  function applyScroll(x:number,y:number){pendingScrollX=Math.max(0,Number(x||0));pendingScrollY=Math.max(0,Number(y||0));try{frame?.contentWindow?.scrollTo(pendingScrollX,pendingScrollY);}catch{}}
  function loadVisual(path:string,x=0,y=0,force=false){if(!frame)return;const safePath=path&&path.startsWith('/')?path:'/';currentPath=safePath;pendingScrollX=Math.max(0,Number(x||0));pendingScrollY=Math.max(0,Number(y||0));if(!force&&frame.dataset.path===safePath){applyScroll(pendingScrollX,pendingScrollY);return;}frame.dataset.path=safePath;visualReady=false;frame.onload=()=>{visualReady=true;try{frame.contentWindow?.scrollTo(pendingScrollX,pendingScrollY);}catch{}};frame.src=visualUrl(safePath);}
  function setViewport(ev:ReplayEvent){if(ev.vw)viewportW=Math.max(240,Math.min(2400,Number(ev.vw)));if(ev.vh)viewportH=Math.max(320,Math.min(2000,Number(ev.vh)));device=ev.device||((viewportW<768)?'mobile':viewportW<1100?'tablet':'desktop');}
  function apply(ev:ReplayEvent){if(ev.kind==='viewport'){setViewport(ev);return;}if(ev.kind==='route')loadVisual(ev.path||currentPath,pendingScrollX,pendingScrollY);if(ev.kind==='snapshot'){setViewport(ev);loadVisual(ev.path||currentPath,Number(ev.x||0),Number(ev.y||0));}if(ev.kind==='pointer'){cursorX=Number(ev.x||0);cursorY=Number(ev.y||0);cursorVisible=true;}if(ev.kind==='scroll')applyScroll(Number(ev.x||0),Number(ev.y||0));if(ev.kind==='click'){cursorX=Number(ev.x||0);cursorY=Number(ev.y||0);cursorVisible=true;clickPulse=false;requestAnimationFrame(()=>{clickPulse=true;setTimeout(()=>clickPulse=false,450);});}}
  function resetTo(ms:number){elapsed=Math.max(0,Math.min(duration,ms));index=0;cursorVisible=false;clickPulse=false;currentPath=data.session.landingPath;pendingScrollX=0;pendingScrollY=0;frame&&delete frame.dataset.path;for(let i=0;i<data.events.length;i++){const rel=Number(data.events[i].t||firstT)-firstT;if(rel>elapsed)break;if(data.events[i].kind==='viewport'||data.events[i].kind==='snapshot')setViewport(data.events[i]);}loadVisual(data.session.landingPath,0,0,true);while(index<data.events.length){const rel=Number(data.events[index].t||firstT)-firstT;if(rel>elapsed)break;apply(data.events[index]);index++;}}
  function loop(now:number){if(!playing)return;elapsed=Math.min(duration,startedElapsed+(now-startedWall)*speed);while(index<data.events.length){const rel=Number(data.events[index].t||firstT)-firstT;if(rel>elapsed)break;apply(data.events[index]);index++;}if(elapsed>=duration){playing=false;return;}raf=requestAnimationFrame(loop);}
  function togglePlay(){if(!data.events.length)return;if(elapsed>=duration)resetTo(0);playing=!playing;if(playing){startedWall=performance.now();startedElapsed=elapsed;raf=requestAnimationFrame(loop);}else cancelAnimationFrame(raf);}
  function seek(value:number){playing=false;cancelAnimationFrame(raf);resetTo(value);}function setSpeed(v:number){speed=v;if(playing){startedWall=performance.now();startedElapsed=elapsed;}}
  onMount(()=>{if(data.events.length)resetTo(0);return()=>cancelAnimationFrame(raf);});
</script>

<header><a class="back" href={`/sessions/${data.session.id}`}>← Nazad na detalje sesije</a><div class="eyebrow">VISUAL SESSION REPLAY · PRIVACY MASKED</div><h1>Replay kupca</h1><p>{new Date(data.session.startedAt).toLocaleString('sr-RS')} · {data.session.utmSource||(data.session.fbclid?'facebook':'direct')} · {currentPath}</p></header>
{#if !data.events.length}<section class="empty"><h2>Nema replay snimka za ovu sesiju</h2><p>Replay počinje tek od tracker deploymenta; stare sesije se ne mogu retroaktivno snimiti.</p></section>{:else}
<section class="player"><div class="toolbar"><button on:click={togglePlay}>{playing?'❚❚ Pauza':'▶ Pusti'}</button><strong>{fmt(elapsed)} / {fmt(duration)}</strong><input aria-label="Replay position" type="range" min="0" max={Math.max(1,duration)} step="100" value={elapsed} on:input={(e)=>seek(Number((e.currentTarget as HTMLInputElement).value))}/><div class="speeds">{#each [0.5,1,2,4] as s}<button class:active={speed===s} on:click={()=>setSpeed(s)}>{s}×</button>{/each}</div></div>
<div class="meta"><span><b>{data.events.length}</b> signala</span><span><b>{data.chunks}</b> paketa</span><span><b>{Math.round(data.bytes/1024)} KB</b> snimljeno</span><span><b>{viewportW}×{viewportH}</b> {device}</span><span class:ready={visualReady}>{visualReady?'STRANICA UČITANA':'UČITAVAM…'}</span></div>
<div class="visual-note"><b>1:1 ponašanje:</b> viewport, kursor/tap, klikovi, scroll, vreme i promena putanje dolaze iz konkretne sesije. Vizuelni sadržaj stranice je bezbedan render TrendyPatike stranice, pa se ne izvršavaju checkout ili forme u playeru.</div>
<div class="stage-wrap"><div class:phone={device==='mobile'} class="device-frame"><div class="stage" style={`width:${viewportW}px;height:${viewportH}px`}><iframe bind:this={frame} title="Session replay" sandbox="allow-same-origin"></iframe>{#if cursorVisible}<div class="cursor" style={`transform:translate(${cursorX}px,${cursorY}px)`}></div>{/if}{#if clickPulse}<div class="pulse" style={`left:${cursorX}px;top:${cursorY}px`}></div>{/if}</div></div></div></section>
<section class="privacy"><b>Privatnost:</b> input, email, telefon, adresa, textarea i contenteditable vrednosti se ne prikazuju. {#if data.recordedSnapshots>0}Sačuvano je {data.recordedSnapshots} istorijskih DOM snapshot-a kao pomoćni zapis.{/if}</section>{/if}

<style>
header{margin-bottom:18px}.back{display:inline-block;color:#8bf048;font-size:12px;margin-bottom:12px}.eyebrow{font-size:10px;color:#7e8897;font-weight:900;letter-spacing:.12em}h1{font-size:34px;margin:4px 0 6px;letter-spacing:-.04em}header p{color:#8f99a8;margin:0}.player{background:#101318;border:1px solid #20242b;border-radius:18px;padding:16px}.toolbar{display:grid;grid-template-columns:auto auto 1fr auto;align-items:center;gap:12px;margin-bottom:10px}.toolbar>button{border:0;border-radius:9px;background:#8bf048;color:#091008;font-weight:900;padding:10px 14px}.toolbar strong{font-size:12px;color:#aeb7c3}.toolbar input{width:100%}.speeds{display:flex;gap:5px}.speeds button{border:1px solid #29303a;background:#0b0e12;color:#8d98a6;border-radius:8px;padding:7px 9px}.speeds button.active{color:#caffb1;border-color:#426735;background:#132012}.meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.meta span{font-size:10px;color:#7f8997;background:#0b0e12;border:1px solid #1f252d;padding:7px 9px;border-radius:99px}.meta span.ready{color:#9ee890;border-color:#2b4d28}.meta b{color:#e8edf4}.visual-note{margin-bottom:12px;padding:10px 12px;border-radius:10px;background:#11170e;border:1px solid #26331e;color:#9db38f;font-size:11px;line-height:1.45}.stage-wrap{overflow:auto;max-height:76vh;background:#050608;border-radius:14px;border:1px solid #20242b;padding:18px}.device-frame{width:max-content;margin:0 auto}.device-frame.phone{padding:10px;border-radius:30px;background:#090b0e;border:1px solid #303640;box-shadow:0 12px 50px rgba(0,0,0,.45)}.stage{position:relative;background:#fff;overflow:hidden;margin:0 auto}.phone .stage{border-radius:20px}iframe{width:100%;height:100%;border:0;background:white;display:block}.cursor{position:absolute;left:0;top:0;width:16px;height:20px;pointer-events:none;z-index:20}.cursor:before{content:'';position:absolute;width:13px;height:18px;background:#111;clip-path:polygon(0 0,100% 67%,57% 72%,78% 100%,62% 100%,43% 76%,10% 100%)}.pulse{position:absolute;width:34px;height:34px;border-radius:50%;border:3px solid #8bf048;transform:translate(-17px,-17px);z-index:19;pointer-events:none;animation:pulse .45s ease-out forwards}.privacy,.empty{margin-top:12px;padding:14px;border-radius:14px;background:#101a10;border:1px solid #213321;color:#9bc88d;font-size:12px;line-height:1.55}@keyframes pulse{from{opacity:1;transform:translate(-17px,-17px) scale(.4)}to{opacity:0;transform:translate(-17px,-17px) scale(1.4)}}@media(max-width:850px){.toolbar{grid-template-columns:1fr 1fr}.toolbar input{grid-column:1/-1}.stage-wrap{padding:8px}.device-frame{transform-origin:top center}}
</style>
