import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { validOrderSql } from '$lib/server/orders';

const DAY = 86400000;
const DAILY_AI_LIMIT = 30;
const AI_MODELS = ['@cf/zai-org/glm-4.7-flash', '@cf/google/gemma-4-26b-a4b-it'] as const;
const pct = (a:number,b:number) => b ? (a/b)*100 : 0;
const fmt = (n:number) => new Intl.NumberFormat('sr-RS',{maximumFractionDigits:1}).format(n);

type Action = { id:string; label:string; kind:'link'|'sync'; href?:string; provider?:'shopify'|'meta'; tone?:'primary'|'warn' };
type AiBinding = { run:(model:string,input:Record<string,unknown>)=>Promise<any> };
type AiMessage = { role:'system'|'user'|'assistant'; content:string };

function parseMeta(raw:unknown){ try{return JSON.parse(String(raw||'{}')) as Record<string,any>;}catch{return{};} }
function dayKey(ms:number){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Belgrade',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ms));}
function zonedStart(key:string){const [y,m,d]=key.split('-').map(Number);let guess=Date.UTC(y,m-1,d);const p=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Belgrade',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess));const n=(t:string)=>Number(p.find(x=>x.type===t)?.value||0);const represented=Date.UTC(n('year'),n('month')-1,n('day'),n('hour'),n('minute'),n('second'));return guess-(represented-guess);}
function rangeWindow(range:string){const now=Date.now(),today=dayKey(now),start=zonedStart(today);if(range==='today')return{key:'today',start,end:now,label:'Danas'};if(range==='yesterday'){const y=dayKey(start-1);return{key:'yesterday',start:zonedStart(y),end:start,label:'Juče'};}if(range==='30d')return{key:'30d',start:now-30*DAY,end:now,label:'30 dana'};return{key:'7d',start:now-7*DAY,end:now,label:'7 dana'};}
function norm(value:unknown){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
const STOP=new Set(['kako','koliko','zasto','sta','tacno','meni','treba','ovo','onaj','ona','koji','koja','koje','ako','radi','funkcionise','ljudi','kupci','kupac','sajt','stranica','analiza','analiziraj','pogledaj']);
function keywords(message:string){return [...new Set(norm(message).split(/\s+/).filter(x=>x.length>=3&&!STOP.has(x)))].slice(0,14);}
function questionIntent(q:string){const n=norm(q);return{dead:/dead|mrtv|ne reag|ne radi/.test(n),rage:/rage|besn|vise puta|frustr/.test(n),atc:/add to cart|atc|korp|korpu|dodaj/.test(n),checkout:/checkout|placan|narudz|porudz|kupovin|odustan/.test(n),meta:/meta|oglas|ads|kampanj|ctr|cpc|cpm|roas/.test(n),replay:/replay|snim|sesij|ponasan/.test(n),product:/pdp|proizvod|patik|model|lot|velicin/.test(n)};}
function relevance(text:string, keys:string[]){const n=norm(text);let score=0;for(const k of keys)if(n.includes(k))score+=k.length>=6?4:2;return score;}
function safeHistory(value:unknown):AiMessage[]{if(!Array.isArray(value))return[];return value.slice(-8).flatMap((r:any)=>{const role=r?.role==='assistant'?'assistant':r?.role==='user'?'user':null;if(!role)return[];const content=String(r?.content||'').trim().slice(0,1600);return content?[{role,content}]:[];});}
function extractAiText(result:any){const c=result?.choices?.[0]?.message?.content;if(typeof c==='string')return c.trim();if(Array.isArray(c))return c.map((x:any)=>typeof x==='string'?x:String(x?.text||x?.content||'')).join('\n').trim();for(const v of [result?.response,result?.result?.response,result?.text,result?.output_text])if(typeof v==='string'&&v.trim())return v.trim();return '';}

function sessionScore(r:any,intent:ReturnType<typeof questionIntent>,keys:string[]){let s=0;const text=[r.landing_path,r.utm_source,r.exit_path,r.exit_label].join(' ');s+=relevance(text,keys)*6;const product=Number(r.product_views||0),atc=Number(r.atc||0),checkout=Number(r.checkout||0),purchased=Boolean(r.purchased),rage=Number(r.rage||0),dead=Number(r.dead||0);if(intent.dead)s+=dead*10;if(intent.rage)s+=rage*8;if(intent.atc){if(product>0&&!atc)s+=18;if(atc)s+=5;}if(intent.checkout){if(atc&&!checkout)s+=14;if(checkout&&!purchased)s+=24;}if(intent.meta&&/facebook|instagram|meta|paid_social|fb/i.test(String(r.utm_source||'')))s+=18;if(intent.product&&product>0)s+=8;if(Number(r.replay_chunks||0)>0)s+=7;s+=Math.min(6,product)+Math.min(5,rage+dead);return s;}

function summarizeCoreEvents(rows:any[], ids:string[]){const by=new Map<string,any[]>();for(const id of ids)by.set(id,[]);for(const r of rows){const sid=String(r.session_id||''),arr=by.get(sid);if(!arr)continue;const m=parseMeta(r.meta_json);const label=String(m.label||m.source||m.target||m.lastInteraction?.label||m.lastInteraction?.target||'').replace(/\s+/g,' ').trim().slice(0,110);arr.push({t:Number(r.event_ts||0),type:String(r.type||''),path:String(r.path||'/').slice(0,180),label,depth:Number(m.depth||0)||undefined,activeSec:m.activeMs!=null?Math.round(Number(m.activeMs||0)/1000):undefined,maxScroll:m.maxScroll!=null?Number(m.maxScroll||0):undefined});}const out=new Map<string,any>();for(const id of ids){const all=(by.get(id)||[]).sort((a,b)=>a.t-b.t),base=all[0]?.t||0;const compact:any[]=[];let lastScroll=-1;for(const e of all){if(e.type==='heartbeat')continue;if(e.type==='scroll_depth'){if(e.depth===lastScroll)continue;lastScroll=e.depth;}compact.push({sec:base?Math.max(0,Math.round((e.t-base)/1000)):0,type:e.type,path:e.path,label:e.label||undefined,depth:e.depth,activeSec:e.activeSec,maxScroll:e.maxScroll});if(compact.length>=38)break;}const exit=[...all].reverse().find(e=>e.type==='page_exit');out.set(id,{timeline:compact,eventCount:all.length,exitPath:exit?.path||'',exitLabel:exit?.label||'',exitActiveSec:exit?.activeSec||0,exitScroll:exit?.maxScroll||0});}return out;}

function replaySummaries(rows:any[], ids:string[]){const map=new Map<string,{routes:Set<string>;clicks:number;clickLabels:Map<string,number>;scrollMax:number;device:string;vw:number;vh:number;first:number;last:number;packets:number;timeline:any[]}>();for(const id of ids)map.set(id,{routes:new Set(),clicks:0,clickLabels:new Map(),scrollMax:0,device:'',vw:0,vh:0,first:Infinity,last:0,packets:0,timeline:[]});for(const row of rows){const id=String(row.session_id||''),g=map.get(id);if(!g)continue;g.packets++;let events:any[]=[];try{events=JSON.parse(String(row.data_json||'[]'));}catch{continue;}for(const ev of events){const t=Number(ev?.t||0);if(t){g.first=Math.min(g.first,t);g.last=Math.max(g.last,t);}if(ev?.kind==='route'&&ev.path){g.routes.add(String(ev.path).slice(0,160));g.timeline.push({t,kind:'route',path:String(ev.path).slice(0,160)});}if(ev?.kind==='viewport'){g.device=String(ev.device||g.device);g.vw=Number(ev.vw||g.vw);g.vh=Number(ev.vh||g.vh);if(ev.path)g.routes.add(String(ev.path).slice(0,160));}if(ev?.kind==='click'){g.clicks++;const label=String(ev.label||'klik bez oznake').replace(/\s+/g,' ').trim().slice(0,100);g.clickLabels.set(label,(g.clickLabels.get(label)||0)+1);g.timeline.push({t,kind:'click',label,x:Number(ev.x||0),y:Number(ev.y||0)});}if(ev?.kind==='scroll'){g.scrollMax=Math.max(g.scrollMax,Number(ev.y||0));if(!g.timeline.length||g.timeline[g.timeline.length-1]?.kind!=='scroll')g.timeline.push({t,kind:'scroll',y:Number(ev.y||0)});}}}return ids.map((id,index)=>{const g=map.get(id)!;const base=Number.isFinite(g.first)?g.first:0;return{ref:`R${index+1}`,sessionId:id,packets:g.packets,durationSec:g.last&&base?Math.round((g.last-base)/1000):0,device:g.device||'unknown',viewport:g.vw&&g.vh?`${g.vw}x${g.vh}`:'unknown',routes:[...g.routes].slice(0,8),clicks:g.clicks,topClicks:[...g.clickLabels.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,count])=>({label,count})),maxScrollY:Math.round(g.scrollMax),timeline:g.timeline.sort((a,b)=>a.t-b.t).slice(0,28).map(e=>({...e,sec:base?Math.max(0,Math.round((e.t-base)/1000)):0,t:undefined}))};});}

function fallbackAnswer(context:any,message:string){const intent=questionIntent(message),target=context.focus?.interactions?.[0],page=context.focus?.pages?.[0],f=context.funnel;if(intent.dead){if(target){const rate=target.clicks?pct(target.dead,target.clicks):0;return `DIREKTAN ODGOVOR\n„${target.label}“ nije automatski pokvaren zato što ima dead-click signal. Vidim ${target.clicks} običnih klikova, ${target.dead} dead i ${target.rage} rage signala${target.sessions?` kroz ${target.sessions} sesija`:''}. To je oko ${fmt(rate)} dead signala na 100 običnih klikova.\n\nŠTA DEAD CLICK KOD NAS ZNAČI\nTracker ga označi kada korisnik klikne interaktivni element, a u narednih ~0,9 s ne vidi promenu URL-a ni DOM mutaciju. Zato funkcionalan „${target.label}“ može dobiti lažni dead signal ako reakcija ide kroz canvas/iframe/shadow DOM, ako promena kasni, ili se vizuelni efekat ne vidi našem observer-u.\n\nŠTA TREBA PROVERITI\nNe bih menjao element samo zbog ovog broja. Prvo proveri fokusirane replay-e i da li posle klika stvarno sledi očekivani rezultat. Ako radi, ovo je false-positive heuristika i treba popraviti detekciju, ne UI.`;}return `DIREKTAN ODGOVOR\nDead click kod ovog trackera znači „klik bez uočene reakcije u narednih ~0,9 s“, ne „element sigurno ne radi“. Za ovo pitanje nisam našao dovoljno precizan label-match u izabranom periodu.`;}if(intent.rage&&target)return `DIREKTAN ODGOVOR\nNajrelevantniji element je „${target.label}“: ${target.rage} rage signala na ${target.clicks} običnih klikova. Rage kod nas znači najmanje 3 brza klika unutar ~900 ms u krugu od 55 px. To jeste signal frustracije, ali ne dokazuje razlog.`;if(intent.checkout)return `DIJAGNOZA\nATC→checkout je ${fmt(f.atcToCheckout)}%, a checkout→preuzeta kupovina ${fmt(f.checkoutToPurchase)}%. ${context.focus?.sessions?.length||0} najrelevantnijih sesija je izdvojeno baš za ovo pitanje.\n\nKONKRETAN SLEDEĆI KORAK\nPregledaj timeline ATC bez checkouta i checkout bez kupovine. Menjaj samo element koji se ponavlja neposredno pre izlaza, ne ceo checkout napamet.`;if(intent.atc)return `DIJAGNOZA\nPDP→ATC je ${fmt(f.pdpToAtc)}%. Fokus analize je ${page?.path||'PDP'}; izdvojeno je ${context.focus?.sessions?.length||0} sesija relevantnih za pitanje.\n\nKONKRETAN SLEDEĆI KORAK\nUporedi gde izlaze PDP sesije bez ATC, koji element klikću poslednji i dokle skroluju. Ako se jedan element ponavlja, menjaj baš njega; neću generički savetovati cenu/CTA bez tog dokaza.`;return `ANALIZA ZA OVO PITANJE\nFunnel: ${f.sessions} sesija, ${f.productViews} PDP, ${f.atc} ATC, ${f.checkout} checkout, ${f.purchased} preuzetih kupovina. Fokusirano je ${context.focus?.pages?.length||0} relevantnih stranica, ${context.focus?.interactions?.length||0} interakcija i ${context.focus?.sessions?.length||0} sesija. AI trenutno nije odgovorio, pa neću dati generičan fix bez dovoljno dokaza.`;}

async function runAi(ai:AiBinding,messages:AiMessage[]){const errors:string[]=[];for(const model of AI_MODELS){try{const result=await ai.run(model,{messages,max_completion_tokens:1600,temperature:0.15});const text=extractAiText(result);if(text)return{text,model,tokens:Number(result?.usage?.total_tokens||result?.usage?.totalTokens||0),errors};errors.push(`${model}: prazan odgovor`);}catch(e){errors.push(`${model}: ${e instanceof Error?e.message:String(e)}`);}}return{text:'',model:'data-fallback',tokens:0,errors};}

export const POST: RequestHandler = async ({ request, platform }) => {
  const env=(platform?.env??{}) as any,db=env.DB as D1Database|undefined;
  if(!db)return json({ok:false,error:'D1 nije dostupan'},{status:503});
  const body=await request.json().catch(()=>({})) as {message?:string;period?:string;history?:unknown};
  const message=String(body.message||'').trim().slice(0,1800);
  if(!message)return json({ok:false,error:'Napiši pitanje.'},{status:400});
  const history=safeHistory(body.history),period=rangeWindow(String(body.period||'7d')),keys=keywords(message),intent=questionIntent(message);
  const dayFrom=new Date(period.start).toISOString().slice(0,10),dayTo=new Date(Math.max(period.start,period.end-1)).toISOString().slice(0,10);

  const [shop,sessions,pagesResult,interactionsResult,topProduct,meta,metaAds,candidates]=await Promise.all([
    db.prepare(`SELECT COUNT(*) orders,COALESCE(SUM(total),0) revenue FROM shopify_orders WHERE ${validOrderSql()} AND created_at>=?1 AND created_at<?2`).bind(period.start,period.end).first<any>(),
    db.prepare(`SELECT COUNT(DISTINCT s.id) sessions,COUNT(DISTINCT CASE WHEN e.type='product_view' THEN s.id END) product_views,COUNT(DISTINCT CASE WHEN e.type='add_to_cart' THEN s.id END) atc,COUNT(DISTINCT CASE WHEN e.type='checkout_started' THEN s.id END) checkout,COUNT(DISTINCT CASE WHEN s.purchased=1 THEN s.id END) purchased,COUNT(DISTINCT CASE WHEN e.type='rage_click' THEN s.id END) rage,COUNT(DISTINCT CASE WHEN e.type='dead_click' THEN s.id END) dead FROM sessions s LEFT JOIN events e ON e.session_id=s.id AND e.event_ts>=?1 AND e.event_ts<?2 WHERE s.started_at>=?1 AND s.started_at<?2`).bind(period.start,period.end).first<any>(),
    db.prepare(`SELECT path,COUNT(DISTINCT CASE WHEN type IN ('page_view','product_view') THEN session_id END) visits,COUNT(DISTINCT CASE WHEN type='page_exit' THEN session_id END) exits,COUNT(DISTINCT CASE WHEN type='add_to_cart' THEN session_id END) atc,COUNT(DISTINCT CASE WHEN type='checkout_started' THEN session_id END) checkout,SUM(CASE WHEN type='rage_click' THEN 1 ELSE 0 END) rage,SUM(CASE WHEN type='dead_click' THEN 1 ELSE 0 END) dead,AVG(CASE WHEN type='page_exit' THEN CAST(json_extract(meta_json,'$.activeMs') AS REAL) END) active_ms,AVG(CASE WHEN type IN ('page_exit','heartbeat') THEN CAST(json_extract(meta_json,'$.maxScroll') AS REAL) END) avg_scroll FROM events WHERE event_ts>=?1 AND event_ts<?2 GROUP BY path HAVING COUNT(DISTINCT CASE WHEN type IN ('page_view','product_view') THEN session_id END)>0 ORDER BY visits DESC LIMIT 40`).bind(period.start,period.end).all(),
    db.prepare(`SELECT path,COALESCE(NULLIF(CAST(json_extract(meta_json,'$.label') AS TEXT),''),NULLIF(CAST(json_extract(meta_json,'$.target') AS TEXT),''),'bez oznake') label,COUNT(DISTINCT session_id) sessions,SUM(CASE WHEN type='click' THEN 1 ELSE 0 END) clicks,SUM(CASE WHEN type='rage_click' THEN 1 ELSE 0 END) rage,SUM(CASE WHEN type='dead_click' THEN 1 ELSE 0 END) dead FROM events WHERE event_ts>=?1 AND event_ts<?2 AND type IN ('click','rage_click','dead_click') GROUP BY path,label ORDER BY (rage+dead) DESC,clicks DESC LIMIT 100`).bind(period.start,period.end).all(),
    db.prepare(`SELECT MAX(i.title) title,COUNT(DISTINCT o.id) orders,SUM(i.line_total) revenue FROM shopify_order_items i JOIN shopify_orders o ON o.id=i.order_id WHERE ${validOrderSql('o')} AND o.created_at>=?1 AND o.created_at<?2 GROUP BY COALESCE(i.product_id,i.title) ORDER BY revenue DESC LIMIT 1`).bind(period.start,period.end).first<any>(),
    db.prepare(`SELECT COALESCE(SUM(spend),0) spend,COALESCE(SUM(impressions),0) impressions,COALESCE(SUM(clicks),0) clicks,COALESCE(SUM(purchases),0) purchases,COALESCE(SUM(purchase_value),0) purchase_value,COALESCE(SUM(link_clicks),0) link_clicks,COALESCE(SUM(landing_page_views),0) landing_views,COALESCE(SUM(add_to_cart),0) atc,COALESCE(SUM(checkouts),0) checkouts FROM meta_daily WHERE day>=?1 AND day<=?2`).bind(dayFrom,dayTo).first<any>(),
    db.prepare(`SELECT MAX(account_name) account_name,MAX(currency) currency,ad_id,MAX(ad_name) ad_name,SUM(spend) spend,SUM(impressions) impressions,SUM(clicks) clicks,SUM(purchases) purchases,SUM(purchase_value) purchase_value FROM meta_daily WHERE day>=?1 AND day<=?2 GROUP BY ad_id ORDER BY spend DESC LIMIT 10`).bind(dayFrom,dayTo).all(),
    db.prepare(`SELECT s.id,s.started_at,s.last_seen_at,s.landing_path,s.utm_source,s.purchased,s.revenue,COUNT(DISTINCT CASE WHEN e.type='product_view' THEN e.event_ts END) product_views,COUNT(DISTINCT CASE WHEN e.type='add_to_cart' THEN e.event_ts END) atc,COUNT(DISTINCT CASE WHEN e.type='checkout_started' THEN e.event_ts END) checkout,COUNT(DISTINCT CASE WHEN e.type='rage_click' THEN e.event_ts END) rage,COUNT(DISTINCT CASE WHEN e.type='dead_click' THEN e.event_ts END) dead,MAX(CASE WHEN e.type='page_exit' THEN e.path END) exit_path,MAX(CASE WHEN e.type='page_exit' THEN COALESCE(json_extract(e.meta_json,'$.lastInteraction.label'),json_extract(e.meta_json,'$.lastInteraction.target'),'') END) exit_label,(SELECT COUNT(*) FROM replay_chunks r WHERE r.session_id=s.id) replay_chunks FROM sessions s LEFT JOIN events e ON e.session_id=s.id AND e.event_ts>=?1 AND e.event_ts<?2 WHERE s.started_at>=?1 AND s.started_at<?2 GROUP BY s.id ORDER BY s.started_at DESC LIMIT 100`).bind(period.start,period.end).all()
  ]);

  const f={sessions:Number(sessions?.sessions||0),productViews:Number(sessions?.product_views||0),atc:Number(sessions?.atc||0),checkout:Number(sessions?.checkout||0),purchased:Number(sessions?.purchased||0),rage:Number(sessions?.rage||0),dead:Number(sessions?.dead||0),pdpToAtc:pct(Number(sessions?.atc||0),Number(sessions?.product_views||0)||Number(sessions?.sessions||0)),atcToCheckout:pct(Number(sessions?.checkout||0),Number(sessions?.atc||0)),checkoutToPurchase:pct(Number(sessions?.purchased||0),Number(sessions?.checkout||0))};
  const pages=(pagesResult.results as any[]).map(r=>({path:String(r.path||'/'),visits:Number(r.visits||0),exits:Number(r.exits||0),exitRate:Number(r.visits||0)?Number(r.exits||0)/Number(r.visits||0)*100:0,atc:Number(r.atc||0),checkout:Number(r.checkout||0),rage:Number(r.rage||0),dead:Number(r.dead||0),activeMs:Number(r.active_ms||0),avgScroll:Number(r.avg_scroll||0)}));
  const interactions=(interactionsResult.results as any[]).map(r=>({path:String(r.path||'/'),label:String(r.label||'bez oznake').slice(0,110),sessions:Number(r.sessions||0),clicks:Number(r.clicks||0),rage:Number(r.rage||0),dead:Number(r.dead||0)}));
  const relevantPages=[...pages].sort((a,b)=>(relevance(`${b.path}`,keys)*100+b.visits)-(relevance(`${a.path}`,keys)*100+a.visits)).slice(0,8);
  const relevantInteractions=[...interactions].sort((a,b)=>(relevance(`${b.label} ${b.path}`,keys)*100+(b.rage+b.dead)*3+b.clicks)-(relevance(`${a.label} ${a.path}`,keys)*100+(a.rage+a.dead)*3+a.clicks)).slice(0,12);
  const cand=(candidates.results as any[]).map(r=>({...r,_score:sessionScore(r,intent,keys)})).sort((a,b)=>b._score-a._score||Number(b.started_at||0)-Number(a.started_at||0)).slice(0,12);
  const ids=cand.map(r=>String(r.id));
  let replayRows:any[]=[],eventRows:any[]=[];
  if(ids.length){const ph=ids.map((_,i)=>`?${i+1}`).join(',');const [rr,er]=await Promise.all([db.prepare(`SELECT session_id,data_json,created_at FROM replay_chunks WHERE session_id IN (${ph}) ORDER BY created_at ASC LIMIT 180`).bind(...ids).all(),db.prepare(`SELECT session_id,type,path,event_ts,meta_json FROM events WHERE session_id IN (${ph}) AND event_ts>=?${ids.length+1} AND event_ts<?${ids.length+2} ORDER BY event_ts ASC LIMIT 2600`).bind(...ids,period.start,period.end).all()]);replayRows=rr.results as any[];eventRows=er.results as any[];}
  const replay=replaySummaries(replayRows,ids),core=summarizeCoreEvents(eventRows,ids);
  const sessionEvidence=cand.map((r,i)=>{const rep=replay[i],c=core.get(String(r.id))||{};return{ref:`R${i+1}`,score:Number(r._score||0),source:String(r.utm_source||'direct'),durationSec:Math.round(Math.max(0,Number(r.last_seen_at||0)-Number(r.started_at||0))/1000),landing:String(r.landing_path||'/'),productViews:Number(r.product_views||0),atc:Number(r.atc||0),checkout:Number(r.checkout||0),purchased:Boolean(r.purchased),fulfilledRevenue:Number(r.revenue||0),rage:Number(r.rage||0),dead:Number(r.dead||0),exitPath:c.exitPath||String(r.exit_path||''),exitLabel:c.exitLabel||String(r.exit_label||''),exitActiveSec:c.exitActiveSec||0,exitScroll:c.exitScroll||0,coreTimeline:c.timeline||[],replay:{available:Number(r.replay_chunks||0)>0,device:rep?.device,viewport:rep?.viewport,routes:rep?.routes,clicks:rep?.clicks,topClicks:rep?.topClicks,maxScrollY:rep?.maxScrollY,durationSec:rep?.durationSec,timeline:rep?.timeline}};});

  const mSpend=Number(meta?.spend||0),mImpressions=Number(meta?.impressions||0),mClicks=Number(meta?.clicks||0),mPurchases=Number(meta?.purchases||0),mValue=Number(meta?.purchase_value||0);
  const context={question:message,period:period.label,questionKeywords:keys,intent,trackerSemantics:{deadClick:'Heuristika: posle klika na interaktivni element čeka se oko 900ms; ako URL ostane isti i MutationObserver ne vidi DOM mutaciju, šalje se dead_click. Ne znači automatski da element ne radi. False-positive je moguć kod canvas/iframe/shadow DOM reakcije, odložene reakcije ili reakcije koju observer ne vidi.',rageClick:'Heuristika: najmanje 3 klika u približno 900ms, treći u krugu manjem od 55px od prvog. To je signal frustracije, ne dokaz uzroka.'},revenueRule:'Prihod i orders uključuju samo Shopify porudžbine koje su FULFILLED i nisu otkazane/refundirane/vraćene; ako postoji shipment status, mora biti završni uspešan status.',shopify:{fulfilledRevenue:Number(shop?.revenue||0),fulfilledOrders:Number(shop?.orders||0),topProduct:topProduct?{title:String(topProduct.title||''),orders:Number(topProduct.orders||0),revenue:Number(topProduct.revenue||0)}:null},funnel:f,focus:{pages:relevantPages,interactions:relevantInteractions,sessions:sessionEvidence},baseline:{topPages:pages.slice(0,8),topInteractions:interactions.slice(0,15)},meta:{spend:mSpend,impressions:mImpressions,clicks:mClicks,purchases:mPurchases,purchaseValue:mValue,ctr:pct(mClicks,mImpressions),cpc:mClicks?mSpend/mClicks:0,cpm:mImpressions?mSpend/mImpressions*1000:0,roas:mSpend?mValue/mSpend:0,linkClicks:Number(meta?.link_clicks||0),landingViews:Number(meta?.landing_views||0),atc:Number(meta?.atc||0),checkouts:Number(meta?.checkouts||0),topAds:(metaAds.results as any[]).map(r=>({name:String(r.ad_name||''),account:String(r.account_name||''),currency:String(r.currency||''),spend:Number(r.spend||0),impressions:Number(r.impressions||0),clicks:Number(r.clicks||0),purchases:Number(r.purchases||0),purchaseValue:Number(r.purchase_value||0)}))}};

  const evidence=[`${period.label}: ${f.sessions} sesija · ${f.productViews} PDP · ${f.atc} ATC · ${f.checkout} checkout · ${f.purchased} preuzetih kupovina`,`${sessionEvidence.filter(s=>s.replay.available).length} od ${sessionEvidence.length} fokusiranih sesija ima replay`];const topInt=relevantInteractions[0];if(topInt)evidence.push(`Fokus element: ${topInt.label} · ${topInt.clicks} klikova · ${topInt.rage} rage · ${topInt.dead} dead`);const topPage=relevantPages[0];if(topPage)evidence.push(`Fokus stranica: ${topPage.path} · ${fmt(topPage.exitRate)}% izlaza · ${fmt(topPage.avgScroll)}% scroll`);
  const actions:Action[]=[{id:'important',label:'Pusti fokusirane replay-e',kind:'link',href:`/sessions?filter=important&range=${period.key}`,tone:'primary'},{id:'heatmaps',label:'Otvori Heatmaps',kind:'link',href:`/heatmaps?range=${period.key}`}];if(intent.meta)actions.unshift({id:'ads',label:'Otvori oglase',kind:'link',href:'/ads',tone:'primary'});if(intent.product||intent.atc)actions.unshift({id:'products',label:'Otvori proizvode',kind:'link',href:'/products',tone:'primary'});actions.push({id:'shop-sync',label:'Osveži Shopify',kind:'sync',provider:'shopify'},{id:'meta-sync',label:'Osveži Meta',kind:'sync',provider:'meta'});

  const utcDay=new Date().toISOString().slice(0,10),usage=await db.prepare('SELECT requests,tokens FROM advisor_usage WHERE day=?1').bind(utcDay).first<any>().catch(()=>null),used=Number(usage?.requests||0),ai=env.AI as AiBinding|undefined;
  let answer='',aiUsed=false,model='data-fallback',tokenUsage=0,aiErrors:string[]=[];
  if(ai&&used<DAILY_AI_LIMIT){const system=`Ti si senior e-commerce CRO analitičar za TrendyPatike. Odgovaraš na srpskom i prvo odgovaraš na TAČNO pitanje vlasnika, bez vraćanja na generički funnel kada pita specifičan element ili signal.\n\nRadi kao istražitelj:\n1) identifikuj šta je pitanje i koji element/podatak mu je relevantan;\n2) koristi focus.pages, focus.interactions i focus.sessions kao primarne dokaze; baseline samo za poređenje;\n3) kada postoji timeline, analiziraj redosled događaja pre i posle problema i citiraj R1, R2... kada ih koristiš;\n4) za dead_click/rage_click obavezno koristi trackerSemantics. Dead click NIJE dokaz da element ne radi; ako element radi, razmotri false-positive;\n5) razlikuj činjenicu, hipotezu i ono što ne znamo. Ne izmišljaj psihologiju kupca;\n6) za pitanje zašto rangiraj 2-4 hipoteze samo ako ih dokazi podržavaju i navedi broj sesija/klikova/replay-a + sigurnost VISOK/SREDNJI/NIZAK;\n7) fix veži za konkretan element/stranicu. Ako nema dokaza, reci NE MENJAJ JOŠ i navedi tačan test;\n8) prihod tretiraj samo po revenueRule.\n\nFormat prilagodi pitanju. Za usko pitanje počni sa DIREKTAN ODGOVOR. Za širu CRO analizu koristi DIJAGNOZA, DOKAZI IZ HEATMAP/REPLAY, NAJVEROVATNIJI UZROCI, KONKRETAN FIX, KAKO MERIMO. Nemoj svaki put ponavljati iste pasuse. Nemoj tvrditi da si vizuelno gledao video — analiziraš event timeline i replay signale.`;const compact=JSON.stringify(context).slice(0,42000);const aiMessages:AiMessage[]=[{role:'system',content:system},...history,{role:'user',content:`TRENUTNO PITANJE: ${message}\n\nPODACI ZA OVO PITANJE:\n${compact}`}];const result=await runAi(ai,aiMessages);answer=result.text;model=result.model;tokenUsage=result.tokens;aiErrors=result.errors;aiUsed=Boolean(answer);await db.prepare(`INSERT INTO advisor_usage(day,requests,tokens,updated_at) VALUES(?1,1,?2,?3) ON CONFLICT(day) DO UPDATE SET requests=advisor_usage.requests+1,tokens=advisor_usage.tokens+excluded.tokens,updated_at=excluded.updated_at`).bind(utcDay,tokenUsage,Date.now()).run().catch(()=>{});}else if(!ai)aiErrors=['Workers AI binding nije dostupan.'];else aiErrors=['Dnevni AI hard-limit je dostignut.'];
  if(!answer)answer=fallbackAnswer(context,message);
  return json({ok:true,title:aiUsed?'AI dubinska analiza':'Analiza iz podataka',answer,evidence,actions,period:period.key,generatedAt:Date.now(),ai:aiUsed,model,replaysReviewed:sessionEvidence.filter(s=>s.replay.available).length,sessionsReviewed:sessionEvidence.length,pagesReviewed:relevantPages.length,interactionsReviewed:relevantInteractions.length,aiRequestsRemaining:Math.max(0,DAILY_AI_LIMIT-used-(ai?1:0)),engineError:aiUsed?'':aiErrors.join(' | ').slice(0,700),limitations:aiUsed?'AI je dobio pitanje-specifične heatmap agregate, fokusirane session timeline/replay događaje, Shopify i Meta podatke. Ne čitamo email, telefon, adresu ni input vrednosti. Direktne izmene teme i dalje traže write dozvolu i odobrenje.':`Pravi AI odgovor nije bio dostupan. Fallback je sada pitanje-specifičan, ali nije zamena za model. ${aiErrors.join(' | ').slice(0,500)}`});
};
