import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { cfg } from "./config.mjs";
import { generateImage } from "./openai.mjs";
import { commitAndPush } from "./git.mjs";

const W=1080,H=1350,GREEN="#037361",WHITE="#F7F7F5",FONT="DejaVu Sans Condensed";
const TEXT_LEFT=56,TEXT_RIGHT=1024,TEXT_WIDTH=TEXT_RIGHT-TEXT_LEFT;
const RENDER_VERSION="kids-editorial-v7-no-ai-text";
function esc(s=""){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function clean(text=""){return String(text).replace(/\s+/g," ").replace(/[.?!]+$/g,"").trim();}
function wrap(text,maxChars=24){const words=clean(text).split(/\s+/).filter(Boolean),lines=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(next.length>maxChars&&line){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);return lines;}
function fitLines(text,{maxLines=4,preferred=108,min=62,maxChars=23}={}){let lines=wrap(text,maxChars);for(const width of [maxChars+2,maxChars+4,maxChars+7,maxChars+10]){if(lines.length<=maxLines)break;lines=wrap(text,width);}lines=lines.slice(0,maxLines);const longest=Math.max(1,...lines.map(x=>x.length));const widthFit=Math.floor(TEXT_WIDTH/(longest*.60));const size=Math.max(min,Math.min(preferred,widthFit));return{lines,size,gap:size+8};}
function textSvg(text,{y=280,preferred=116,min=66,maxLines=4,maxChars=22,accentFrom=.62}={}){const{lines,size,gap}=fitLines(text,{maxLines,preferred,min,maxChars});const accentStart=Math.max(0,Math.min(lines.length-1,Math.floor(lines.length*accentFrom)));return lines.map((line,i)=>`<text x="${TEXT_LEFT}" y="${y+i*gap}" font-family="${FONT}" font-size="${size}" font-weight="900" fill="${i>=accentStart?GREEN:WHITE}" letter-spacing="-2">${esc(line.toUpperCase())}</text>`).join("\n");}
function supportTextSvg(text,{y=930,maxLines=3}={}){const{lines,size,gap}=fitLines(text,{maxLines,preferred:76,min:58,maxChars:25});return lines.map((line,i)=>`<text x="${TEXT_LEFT}" y="${y+i*gap}" font-family="${FONT}" font-size="${size}" font-weight="900" fill="${i===lines.length-1?GREEN:WHITE}" letter-spacing="-1.5">${esc(line.toUpperCase())}</text>`).join("\n");}
function fixedFrameSvg(){return `<defs><linearGradient id="leftShade" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stop-color="#000" stop-opacity="0.84"/><stop offset="50%" stop-color="#000" stop-opacity="0.34"/><stop offset="100%" stop-color="#000" stop-opacity="0.04"/></linearGradient><linearGradient id="bottomShade" x1="0" y1="0" x2="0" y2="1"><stop offset="55%" stop-color="#000" stop-opacity="0"/><stop offset="80%" stop-color="#000" stop-opacity="0.28"/><stop offset="100%" stop-color="#000" stop-opacity="0.90"/></linearGradient></defs><rect width="${W}" height="${H}" fill="url(#leftShade)"/><rect width="${W}" height="${H}" fill="url(#bottomShade)"/><rect x="13" y="13" width="${W-26}" height="${H-26}" fill="none" stroke="${GREEN}" stroke-width="3"/><text x="144" y="101" font-family="${FONT}" font-size="31" font-weight="900" fill="${WHITE}" letter-spacing="2">TRENDYPATIKE</text><line x1="48" y1="145" x2="1032" y2="145" stroke="${GREEN}" stroke-width="2"/><line x1="48" y1="1248" x2="1032" y2="1248" stroke="${GREEN}" stroke-width="2"/><text x="56" y="1302" font-family="${FONT}" font-size="31" font-weight="900" fill="${WHITE}" letter-spacing="0.8">TRENDYPATIKE.COM</text>`;}
function coverMainText(post){const h=(post.cover?.headline_lines||[]).map(x=>clean(x.text)).filter(Boolean).join(" ");return h||clean(post.cover?.subheadline)||clean(post.topic_title);}
function coverOverlay(post){const main=coverMainText(post),support=clean(post.cover?.subheadline);return `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">${fixedFrameSvg()}${textSvg(main,{y:280,preferred:120,min:68,maxLines:4,maxChars:21})}${support?supportTextSvg(support,{y:940,maxLines:3}):""}</svg>`;}
function factsOverlay(post){const text=clean(post.slide2?.facts?.[0]?.text);return `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">${fixedFrameSvg()}${textSvg(text,{y:300,preferred:120,min:68,maxLines:5,maxChars:22})}</svg>`;}
function impactOverlay(post){const text=clean(post.slide3?.facts?.[0]?.text);return `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">${fixedFrameSvg()}${textSvg(text,{y:300,preferred:120,min:68,maxLines:5,maxChars:22})}</svg>`;}
async function logoBuffer(){return sharp(path.resolve("assets/logo-mark-white.png")).resize({width:70}).png().toBuffer();}
function finalPrompt(base,i){const composition=i===0?"Place the exact main subject mostly on the right or lower-right, leaving clean dark negative space on the left and upper-left for our overlay text.":"Compose the exact subject prominently center-right or lower-right while leaving clean dark negative space for our overlay text.";return `VISUAL SCENE BRIEF ONLY. DO NOT WRITE OR DISPLAY ANY WORDS FROM THIS BRIEF IN THE IMAGE:\n${base}\n\nCreate only the photographic scene described above. The scene must clearly show the exact sneaker, person, sport, object, place, invention, event or comparison requested by the brief. Never substitute a generic sneaker when a specific model or historical object is requested. ${composition}\n4:5 vertical portrait, premium dark sneaker editorial photography, believable cinematic lighting, realistic materials, strong visual impact. ABSOLUTELY NO WRITTEN LANGUAGE IN THE GENERATED IMAGE: no captions, no headlines, no letters, no numbers, no labels, no signs, no posters, no website text, no random glyphs, no watermark, no TrendyPatike branding or frame. The only typography will be added later by code.`;}
function neutralSafePrompt(i,base){const composition=i===0?"subject mostly right/lower-right with empty dark space left and upper-left":"subject center-right/lower-right with empty dark space left";return `Create a clean 4:5 dark editorial sports photograph based only on this visual scene brief: ${base}. Show the exact specific visual subject, not a generic substitute. ${composition}. ABSOLUTELY NO TEXT OR WRITING OF ANY KIND: no words, letters, numbers, signs, labels, captions, logos with lettering, watermarks, website text or random glyphs. Realistic, kid-friendly, visually striking.`;}
function localFallbackSvg(i){const shift=i*30;return `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg"><defs><radialGradient id="g" cx="78%" cy="62%" r="54%"><stop offset="0%" stop-color="${GREEN}" stop-opacity=".24"/><stop offset="100%" stop-color="#050706" stop-opacity="0"/></radialGradient></defs><rect width="${W}" height="${H}" fill="#050706"/><rect width="${W}" height="${H}" fill="url(#g)"/><path d="M590 ${820+shift} C674 ${748+shift},742 ${700+shift},798 ${642+shift} L886 ${690+shift} C922 ${710+shift},950 ${760+shift},970 ${812+shift} L1020 ${847+shift} C1040 ${864+shift},1028 ${902+shift},994 ${914+shift} C884 ${948+shift},742 ${952+shift},628 ${927+shift} C586 ${918+shift},560 ${884+shift},570 ${850+shift} Z" fill="#252a28" stroke="#aeb5b2" stroke-opacity=".28" stroke-width="3"/></svg>`;}
async function localFallbackBuffer(i){return sharp(Buffer.from(localFallbackSvg(i))).png().toBuffer();}
async function usableImage(file,{width=null,height=null,format=null,minSize=1000}={}){try{const stat=await fs.stat(file);if(!stat.isFile()||stat.size<minSize)return false;const meta=await sharp(file).metadata();if(!meta.width||!meta.height)return false;if(width&&meta.width!==width)return false;if(height&&meta.height!==height)return false;if(format&&!([].concat(format).includes(meta.format)))return false;return true;}catch{return false;}}
async function checkpointBestEffort(files,message){if(process.env.GITHUB_ACTIONS!=="true"||cfg.dryRun)return;try{commitAndPush(files,message,6);}catch(err){console.warn(`[checkpoint] ${message} could not be pushed yet: ${err.message}`);}}
async function renderSlide(source,overlay,logo,outPath){await sharp(source).resize(W,H,{fit:"cover",position:"attention"}).composite([{input:Buffer.from(overlay),left:0,top:0},{input:logo,left:52,top:47}]).jpeg({quality:94,chromaSubsampling:"4:4:4"}).toFile(outPath);if(!(await usableImage(outPath,{width:W,height:H,format:["jpeg","jpg"],minSize:10000})))throw new Error(`Rendered slide failed integrity check: ${outPath}`);}
export async function generateAndRender(post,outputDir){await fs.mkdir(outputDir,{recursive:true});const logo=await logoBuffer();const overlays=[coverOverlay(post),factsOverlay(post),impactOverlay(post)];const outputs=[];const slideCount=Math.max(1,Math.min(3,Number(post.slide_count)||1));for(let i=0;i<slideCount;i++){const number=String(i+1).padStart(2,"0"),sourcePath=path.join(outputDir,`${number}-source-${RENDER_VERSION}.png`),outPath=path.join(outputDir,`${number}.jpg`);if(!(await usableImage(sourcePath,{format:"png",minSize:1000}))){let imageBuffer;if(post.force_local_images){imageBuffer=await localFallbackBuffer(i);}else{const primary=finalPrompt(post.image_prompts[i],i),fallback=`${primary}\nIf a named public figure is difficult to depict, use an era-appropriate scene only when the person is not essential. Never replace a specific product comparison with an unrelated generic shoe. Keep the image completely free of writing.`,safe=neutralSafePrompt(i,post.image_prompts[i]);try{imageBuffer=await generateImage(primary,fallback,safe);}catch(err){console.warn(`[image] AI unavailable for slide ${i+1}; local fallback: ${err.message}`);imageBuffer=await localFallbackBuffer(i);}}await fs.writeFile(sourcePath,imageBuffer);if(!(await usableImage(sourcePath,{format:"png",minSize:1000})))throw new Error(`Source image ${i+1} could not be decoded`);await checkpointBestEffort([sourcePath],`Checkpoint TrendyPatike source ${i+1} ${RENDER_VERSION}`);}await renderSlide(sourcePath,overlays[i],logo,outPath);outputs.push(outPath);await checkpointBestEffort([outPath],`Checkpoint TrendyPatike rendered slide ${i+1} ${RENDER_VERSION}`);}return outputs;}
export async function runRenderSelfTest(){const post={slide_count:3,topic_title:"Kako je Stan Smith dobio ime",cover:{headline_lines:[{text:"OVA PATIKA SE PRVO",accent:false},{text:"ZVALA HAILLET",accent:true}],subheadline:"Tek kasnije je postala Stan Smith."},slide2:{headline_lines:[{text:"",accent:false}],facts:[{tag:"",text:"Napravljena je za francuskog tenisera Roberta Hailleta."}]},slide3:{headline_lines:[{text:"",accent:false}],facts:[{tag:"",text:"Posle je dobila ime Stan Smith."}],question:""},image_prompts:["shoe on tennis court","French tennis player and shoe","before and after sneaker"]};const base=await sharp({create:{width:W,height:H,channels:3,background:"#111111"}}).png().toBuffer(),logo=await logoBuffer(),overlays=[coverOverlay(post),factsOverlay(post),impactOverlay(post)];for(const overlay of overlays){const buffer=await sharp(base).composite([{input:Buffer.from(overlay),left:0,top:0},{input:logo,left:52,top:47}]).jpeg({quality:80}).toBuffer();const meta=await sharp(buffer).metadata();if(meta.width!==W||meta.height!==H||meta.format!=="jpeg")throw new Error("Offline carousel render self-test failed");}}
